config/routes.rb
Rails.application.routes.draw do

  get 'games/start'

  get 'games/current'

  get 'games/join'

  get 'people/friends'

  get 'people/draft'

  get 'people/groups'

  get 'people/teams'

  get 'people/search'

  get 'people/find'

  get 'site/login'

  get 'site/home'
  get 'site/index'

  post 'site/home'

  get 'site/account'

  get 'site/games'

  get 'site/people'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def start
    @header_title = "Start a Game"
  end

  def current
    @header_title = "My Games"
  end

  def join
    @header_title = "Join a Game"
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  @header_title = "SIGN IN"
  end


end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def friends
    @header_title="Search Contacts"
  end

  def groups
    @header_title="My Friend Groups"
  end

  def teams
    @header_title="My Teams"
  end

  def draft
    @header_title="Draft Players"
  end

  def find
    @header_title="Become a Free Agent"
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def home
    @header_title = "Messages"
  end

  def account
    @header_title = "Account Management"
  end

  def games
    @header_title = "Games"
  end

  def people
    @header_title = "People"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/games/join.html.erb
<h1>Games#join</h1>
<p>Find me in app/views/games/join.html.erb</p>

app/views/games/start.html.erb
<label for="select-choice-0" class="select">Sport:</label>
<select name="select-choice-0" id="select-choice-0">
  <option value="standard">Basketball</option>
  <option value="rush">Flag Football</option>
  <option value="express">Tennis</option>
  <option value="overnight">Volleyball</option>
</select>
<br />
<label for="selectdate" class="select">Date:</label>
<input type="date" name="selectdate" id="date" value=""  />

<label for="start-time" class="select">Start Time:</label>
<select name="start-time" id="start-time-0">
  <option value="standard">12</option>
  <option value="rush">1</option>
  <option value="express">2</option>
  <option value="overnight">3</option>
</select>
<select name="select-choice-0" id="select-choice-0">
  <option value="standard">00</option>
  <option value="rush">15</option>
  <option value="express">30</option>
  <option value="overnight">45</option>
</select>
<select name="select-choice-0" id="select-choice-0">
  <option value="standard">AM</option>
  <option value="rush">PM</option>
</select>

app/views/layouts/application.html.erb
</head>
<!DOCTYPE html>
<html>
<head>
  <title>DrafmeFrontend</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript">
$(document).ready(function(){
resizeDiv();
});

window.onresize = function(event) {
resizeDiv();
}

function resizeDiv() {
vpw = $(window).width();
vph = $(window).height();
$(‘#somediv’).css({‘height’: vph + ‘px’});
}

  </script>
</head>
<body>

    <div data-role="header">
        <h1><%= @header_title %></h1>
        <a href="#nav-panel" data-icon="bars" data-iconpos="notext">Menu</a>
    </div><!-- /header -->
    <div role="main" class="ui-content jqm-content jqm-fullwidth">
      <%= yield %>
    </div><!-- /content -->
    <div data-role="panel" data-display="overlay" data-theme="a" id="nav-panel">
        <ul data-role="listview" data-icon="false">
            <li data-role="list-divider">Walter Han</li>
            <li><%= link_to 'Home', site_index_path %></li>
            <li><%= link_to 'Events', site_home_path %></li>
            <li><%= link_to 'Messages', site_home_path %><span class="ui-li-count">22</span></li>
            <li><%= link_to 'Update Info', site_account_path %></li>
            <li><%= link_to 'Account Settings', site_account_path %></li>
            <li data-role="list-divider">Games</li>
            <li><%= link_to 'Start a Game', games_start_path %></li>
            <li><%= link_to 'My Games', games_current_path %></li>
            <li><%= link_to 'Join a Game', games_join_path %></li>
            <li data-role="list-divider">People</li>
            <li><%= link_to 'Friends', people_friends_path %></li>
            <li><%= link_to 'Friend Groups', people_groups_path %></li>
            <li><%= link_to 'Teams', people_teams_path %></li>
            <li data-role="list-divider">Draft Central</li>
            <li><%= link_to 'Draft Player', people_draft_path %></li>
            <li><%= link_to 'My Free Agency', people_find_path %></li>
        </ul>
    </div><!-- /panel -->


</body>
</html>

app/views/layouts/site.html.erb
</head>
<!DOCTYPE html>
<html>
<head>
  <title>DrafmeFrontend</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript">
$(document).ready(function(){
resizeDiv();
});

window.onresize = function(event) {
resizeDiv();
}

function resizeDiv() {
vpw = $(window).width();
vph = $(window).height();
$(‘#somediv’).css({‘height’: vph + ‘px’});
}
  </script>
</head>
<body>

<div data-role="header" data-position="fixed">
        <h1><%= @header_title %></h1>
</div>

<div data-role="content">
<%= yield %>
</div>
<div data-role="footer" data-position="fixed">
        <div data-role="navbar">
          <ul>
            <li><a href='javascript: history.back()' class="ui-btn ui-icon-back ui-btn-icon-top">Back</a></li>
            <li><%= link_to 'Home', site_home_path,  :class =>"ui-btn ui-icon-home ui-btn-icon-top" %></li>
            <li><%= link_to 'Games', site_games_path, :class =>"ui-btn ui-icon-bullets ui-btn-icon-top" %></li>
            <li><%= link_to 'People', site_people_path, :class =>"ui-btn ui-icon-edit ui-btn-icon-top" %></li>
            <li><%= link_to 'Account', site_account_path, :class =>"ui-btn ui-icon-user ui-btn-icon-top" %></li>
          </ul>
        </div>
</div>

</body>
</html>

app/views/login/index.html.erb
<%= form_tag(controller: "site", action: "home") do %>
        <input type="text" id="login_name" placeholder="Username or email" />
        <input type="password" id="login_password" placeholder="Password" />
        <%= submit_tag("Done") %>
<% end %>

app/views/people/draft.html.erb
<h1>People#draft</h1>
<p>Find me in app/views/people/draft.html.erb</p>

app/views/people/find.html.erb
<h1>People#find</h1>
<p>Find me in app/views/people/find.html.erb</p>

app/views/people/friends.html.erb
<ul data-role="listview" data-filter="true" data-autodividers="true" data-inset="false">
        <li><a href="#">Jay Z</a></li>
        <li><a href="#">Jack Johnson</a></li>
        <li><a href="#">Jonson Tsai</a></li>
        <li><a href="#">Paul Ng</a></li>
        <li><a href="#">Paul McCartney</a></li>
        <li><a href="#">Shing Hong Yip</a></li>
        <li><a href="#">Steve Nash</a></li>
        <li><a href="#">Walter Han</a></li>
        <li><a href="#">Wale</a></li>
</ul>

app/views/people/groups.html.erb
<div data-role="collapsible-set">

<ul data-role="listview" data-collapsed="false"><li>asdf</li><li>123</li><ul>
	
</div>

app/views/people/teams.html.erb
<h1>People#teams</h1>
<p>Find me in app/views/people/teams.html.erb</p>

app/views/site/account.html.erb
<h1>Site#account</h1>
<p>Find me in app/views/site/account.html.erb</p>

app/views/site/games.html.erb
<ul data-role="listview" data-inset="true" data-filter="false">
        <li><%= link_to 'Start a Game', games_start_path %></li>
        <li><%= link_to 'My Games', games_current_path %></li>
        <li><%= link_to 'Join Game', games_join_path %></li>
</ul>

app/views/site/home.html.erb
<div data-role="collapsible" data-theme="b" data-content-theme="c" id="outer-collapsible" data-inset="false" data-collapsed-icon = "arrow-d" data-iconpos = "right" data-expanded-icon="arrow-u" >
    <h2>Notifications</h2>    
	<ul data-role="listview" data-mini="true">
            <li data-icon="delete">
		<a>Please verify your email address</a>
	    </li>
	    <li data-icon="delete">
		<a>Please verify your credit card number</a>
	    </li>

	</ul>
</div>

<div data-role="collapsible" data-theme="b" data-content-theme="c" id="outer-collapsible" data-inset="false" data-collapsed-icon = "arrow-d" data-iconpos = "right" data-expanded-icon="arrow-u">
    <h2>Messages</h2>    
	<ul data-role="listview">
	    <li>
		<h3>Shing Hong Yip</h3>
		<p>Me love you long time baby xoxo</p>
		<p class="ui-li-aside"><strong>6:24</strong>PM</p>
	    </li>
	    <li>
		<h3>Jonson Tsai</h3>
		<p>Lolol</p>
		<p class="ui-li-aside"><strong>6:24</strong>PM</p>
	    </li>        
	</ul>
</div>
<div data-role="collapsible" data-theme="b" data-content-theme="c" id="outer-collapsible" data-inset="false" data-collapsed-icon = "arrow-d" data-iconpos = "right" data-expanded-icon="arrow-u">
    <h2>Calendar</h2>    
	<ul data-role="listview">
	    <li>
		<h3>Stephen Weber</h3>
		<p><strong>You've been invited to a meeting at Filament Group in Boston, MA</strong></p>
		<p>Hey Stephen, if you're available at 10am tomorrow, we've got a meeting with the jQuery team.</p>
		<p class="ui-li-aside"><strong>6:24</strong>PM</p>
	    </li>
	    <li>
		<h3>Stephen Weber</h3>
		<p><strong>You've been invited to a meeting at Filament Group in Boston, MA</strong></p>
		<p>Hey Stephen, if you're available at 10am tomorrow, we've got a meeting with the jQuery team.</p>
		<p class="ui-li-aside"><strong>6:24</strong>PM</p>
	    </li>        
	</ul>
</div>

app/views/site/index.html.erb
<h1>DRAFT.ME</h1>
<p>Some picture and logo go here</p>
<br /><br /><br />

<div data-role="footer" data-position="fixed">
  <div data-role="navbar">
  <ul >
            <li><%= link_to 'Messages', site_home_path,  :class =>"ui-btn ui-icon-mail ui-btn-icon-top" %></li>
            <li><%= link_to 'Games', site_games_path, :class =>"ui-btn ui-icon-bullets ui-btn-icon-top" %></li>
            <li><%= link_to 'People', site_people_path, :class =>"ui-btn ui-icon-edit ui-btn-icon-top" %></li>
            <li><%= link_to 'Account', site_account_path, :class =>"ui-btn ui-icon-user ui-btn-icon-top" %></li>
        </ul>
  </div>
</div>

app/views/site/people.html.erb
<ul data-role="listview" data-filter="false" data-inset="true">
        <li data-role="list-divider">Friends</li>
	<li><%= link_to 'Search', people_friends_path %></li>
	<li><%= link_to 'Friend Groups', people_groups_path %></li>
	<li><%= link_to 'Teams', people_teams_path %></li>
</ul>
<ul data-role="listview" data-filter="false" data-inset="true">
        <li data-role="list-divider">Draft and Free Agency</li>
	<li><%= link_to 'Draft People', people_draft_path %></li>
	<li><%= link_to 'Join Free Agency', people_find_path %></li>
</ul>